### ISSUE TITLE
Plugin doesn't compile with Qt Creator 3.3.0

### ISSUE THREAD

**Issue by stonemaster** [Groterik/qtcreator-dubmanager#3]
Latest release of QtC produces errors:

In file included from /usr/include/x86_64-linux-gnu/qt5/QtCore/QtGlobal:1:0,
                 from dubprojectmanager_global.h:4,
                 from dubprojectmanagerplugin.h:4,
                 from dubprojectmanagerplugin.cpp:1:
dubprojectmanagerplugin.cpp:67:1: error: expected ‘;’ at end of input
 Q_EXPORT_PLUGIN2(DubProjectManager, DubProjectManagerPlugin)
 ^
dubprojectmanagerplugin.cpp:67:1: error: static assertion failed: Old plugin system used
 Q_EXPORT_PLUGIN2(DubProjectManager, DubProjectManagerPlugin)
 ^
Makefile:582: recipe for target '.obj/release-shared/dubprojectmanagerplugin.o' failed
make: **\* [.obj/release-shared/dubprojectmanagerplugin.o] Error 1
